### ISSUE TITLE
Access forbidden,

### ISSUE THREAD

**Issue by solsoccer** [exiled-apes/candy-machine-mint#201]
Unhandled Rejection (Error): failed to get balance of account Forbidden:  {"jsonrpc":"2.0","error":{"code": 403, "message":"Access forbidden, contact your app developer or support@rpcpool.com."},

**Comment by solsoccer** [comment]
Hi Guys anyone getting this issue ?

**Comment by BeeBop21** [comment]
Yes. localhost3000 launches in browser after 'yarn start' cmd, shows 'Connect' button, but as soon as I connect my wallet, the page reloads with the same error you posted. Tried removing candy machine mint and starting git clone over, cleared temp files, cookies, restarted computer... same problem. Was not doing this a couple hours ago. HELP!

**Comment by solsoccer** [comment]
yes i belive something is really broken with candy machine mint 
@levicook can you help please ASAP .. something wrong  , i belive its with candymachines

**Comment by solsoccer** [comment]
all rcp calls are falling with below error @levicook 
03 Forbidden:  {"jsonrpc":"2.0","error":{"code": 403, "message":"Access forbidden, contact your app developer or support@rpcpool.com."}

**Comment by BeeBop21** [comment]
Hi @levicook, this is what I get when connecting my wallet. Thanks!
![Capture_candymachine](https://user-images.githubusercontent.com/94882521/146929762-a9417e80-f552-4239-baa1-e9add122f592.PNG)

**Comment by FlyingMonkes** [comment]
I am getting the same thing. Anyone having any luck?

**Comment by stakeconomy** [comment]
The script is abusing an endpoint that is dedicated for explorer.solana.com.

**Comment by FlyingMonkes** [comment]
> The script is abusing an endpoint that is dedicated for explorer.solana.com.

Sorry, Im new to all this. Do you know of a way to fix it? Or what I can look into to fix it?

**Comment by BeeBop21** [comment]
> The script is abusing an endpoint that is dedicated for explorer.solana.com.

Thank you. I'll get my own rpc host and update here it solves the issue.

**Comment by theMausmara** [comment]
Im running exactly same problem.

**Comment by jonwretlind** [comment]
Looks like there is an "uncaught promise error"?  This is what I am getting from my developer tools console.

connection.ts:2172 Uncaught (in promise) Error: failed to get balance of account 3QySa22MnWJTP1HbgF6hacQ8PXJeFwkF2ZNTZTMFPE1r: Error: 403 Forbidden:  {"jsonrpc":"2.0","error":{"code": 403, "message":"Access forbidden, contact your app developer or support@rpcpool.com."}, "id": "f7f93027-ee56-4265-a504-4546316c3deb" } 

    at connection.ts:2172

**Comment by FlyingMonkes** [comment]
> Im running exactly same problem.

Okay so I just talked to a dev from another project as well as emailed support@rpcpool.com. Looks like they have blocked using https://explorer-api.mainnet-beta.solana.com as the REACT_APP_SOLANA_RPC_HOST. If you go to https://www.quicknode.com/. Create an account and then create a node for SOLANA it will give you a URL. Put that URL in the REACT_APP_SOLANA_RPC_HOST value.

So instead of:
REACT_APP_SOLANA_RPC_HOST=https://explorer-api.mainnet-beta.solana.com
It will be:
REACT_APP_SOLANA_RPC_HOST="whatever url they give you from quick node"

This fixed the issue for me.

**Comment by FlyingMonkes** [comment]
> Looks like there is an "uncaught promise error"? This is what I am getting from my developer tools console.
> 
> connection.ts:2172 Uncaught (in promise) Error: failed to get balance of account 3QySa22MnWJTP1HbgF6hacQ8PXJeFwkF2ZNTZTMFPE1r: Error: 403 Forbidden: {"jsonrpc":"2.0","error":{"code": 403, "message":"Access forbidden, contact your app developer or [support@rpcpool.com](mailto:support@rpcpool.com)."}, "id": "f7f93027-ee56-4265-a504-4546316c3deb" }
> 
> ```
> at connection.ts:2172
> ```

My fix above should fix this as well. It all stems from the same thing. Hope this helps :)

**Comment by jakewhiteley** [comment]
`https://solana-api.projectserum.com/` can be used as well.

**Comment by solsoccer** [comment]
> Reference

this solved my issues

**Comment by stakeconomy** [comment]
Can someone replace the endpoint in the code with a PR?

**Comment by sswils211** [comment]
I put in the url from quicknode.com and tried the projectserum one, but I still get the same error
